import type { ComboboxOption } from "~/components/ui/inputs/combobox";
import type { SelectOption } from "~/components/ui/inputs/select";


export const DEGREE_OPTIONS: SelectOption[] = [
  { key: "highschool", value: "highschool", label: "High School" },
  { key: "associates", value: "associates", label: "Associate's" },
  { key: "bachelors", value: "bachelors", label: "Bachelor's" },
  { key: "masters", value: "masters", label: "Master's" },
  { key: "doctorate", value: "doctorate", label: "Doctorate" },
];

export const COUNTRY_OPTIONS: ComboboxOption[] = [
  { key: "Afghanistan", value: "Afghanistan", label: "Afghanistan" },
  { key: "Albania", value: "Albania", label: "Albania" },
  { key: "Algeria", value: "Algeria", label: "Algeria" },
  { key: "Andorra", value: "Andorra", label: "Andorra" },
  { key: "Angola", value: "Angola", label: "Angola" },
  { key: "Antigua and Barbuda", value: "Antigua and Barbuda", label: "Antigua and Barbuda" },
  { key: "Argentina", value: "Argentina", label: "Argentina" },
  { key: "Armenia", value: "Armenia", label: "Armenia" },
  { key: "Australia", value: "Australia", label: "Australia" },
  { key: "Austria", value: "Austria", label: "Austria" },
  { key: "Azerbaijan", value: "Azerbaijan", label: "Azerbaijan" },
  { key: "Bahamas", value: "Bahamas", label: "Bahamas" },
  { key: "Bahrain", value: "Bahrain", label: "Bahrain" },
  { key: "Bangladesh", value: "Bangladesh", label: "Bangladesh" },
  { key: "Barbados", value: "Barbados", label: "Barbados" },
  { key: "Belarus", value: "Belarus", label: "Belarus" },
  { key: "Belgium", value: "Belgium", label: "Belgium" },
  { key: "Belize", value: "Belize", label: "Belize" },
  { key: "Benin", value: "Benin", label: "Benin" },
  { key: "Bhutan", value: "Bhutan", label: "Bhutan" },
  { key: "Bolivia", value: "Bolivia", label: "Bolivia" },
  { key: "Bosnia and Herzegovina", value: "Bosnia and Herzegovina", label: "Bosnia and Herzegovina" },
  { key: "Botswana", value: "Botswana", label: "Botswana" },
  { key: "Brazil", value: "Brazil", label: "Brazil" },
  { key: "Brunei", value: "Brunei", label: "Brunei" },
  { key: "Bulgaria", value: "Bulgaria", label: "Bulgaria" },
  { key: "Burkina Faso", value: "Burkina Faso", label: "Burkina Faso" },
  { key: "Burundi", value: "Burundi", label: "Burundi" },
  { key: "Côte d'Ivoire", value: "Côte d'Ivoire", label: "Côte d'Ivoire" },
  { key: "Cabo Verde", value: "Cabo Verde", label: "Cabo Verde" },
  { key: "Cambodia", value: "Cambodia", label: "Cambodia" },
  { key: "Cameroon", value: "Cameroon", label: "Cameroon" },
  { key: "Canada", value: "Canada", label: "Canada" },
  { key: "Central African Republic", value: "Central African Republic", label: "Central African Republic" },
  { key: "Chad", value: "Chad", label: "Chad" },
  { key: "Chile", value: "Chile", label: "Chile" },
  { key: "China", value: "China", label: "China" },
  { key: "Colombia", value: "Colombia", label: "Colombia" },
  { key: "Comoros", value: "Comoros", label: "Comoros" },
  { key: "Congo (Congo-Brazzaville)", value: "Congo (Congo-Brazzaville)", label: "Congo (Congo-Brazzaville)" },
  { key: "Costa Rica", value: "Costa Rica", label: "Costa Rica" },
  { key: "Croatia", value: "Croatia", label: "Croatia" },
  { key: "Cuba", value: "Cuba", label: "Cuba" },
  { key: "Cyprus", value: "Cyprus", label: "Cyprus" },
  { key: "Czechia (Czech Republic)", value: "Czechia (Czech Republic)", label: "Czechia (Czech Republic)" },
  { key: "Democratic Republic of the Congo", value: "Democratic Republic of the Congo", label: "Democratic Republic of the Congo" },
  { key: "Denmark", value: "Denmark", label: "Denmark" },
  { key: "Djibouti", value: "Djibouti", label: "Djibouti" },
  { key: "Dominica", value: "Dominica", label: "Dominica" },
  { key: "Dominican Republic", value: "Dominican Republic", label: "Dominican Republic" },
  { key: "Ecuador", value: "Ecuador", label: "Ecuador" },
  { key: "Egypt", value: "Egypt", label: "Egypt" },
  { key: "El Salvador", value: "El Salvador", label: "El Salvador" },
  { key: "Equatorial Guinea", value: "Equatorial Guinea", label: "Equatorial Guinea" },
  { key: "Eritrea", value: "Eritrea", label: "Eritrea" },
  { key: "Estonia", value: "Estonia", label: "Estonia" },
  { key: "Eswatini (fmr. Swaziland)", value: "Eswatini (fmr. Swaziland)", label: "Eswatini (fmr. Swaziland)" },
  { key: "Ethiopia", value: "Ethiopia", label: "Ethiopia" },
  { key: "Fiji", value: "Fiji", label: "Fiji" },
  { key: "Finland", value: "Finland", label: "Finland" },
  { key: "France", value: "France", label: "France" },
  { key: "Gabon", value: "Gabon", label: "Gabon" },
  { key: "Gambia", value: "Gambia", label: "Gambia" },
  { key: "Georgia", value: "Georgia", label: "Georgia" },
  { key: "Germany", value: "Germany", label: "Germany" },
  { key: "Ghana", value: "Ghana", label: "Ghana" },
  { key: "Greece", value: "Greece", label: "Greece" },
  { key: "Grenada", value: "Grenada", label: "Grenada" },
  { key: "Guatemala", value: "Guatemala", label: "Guatemala" },
  { key: "Guinea", value: "Guinea", label: "Guinea" },
  { key: "Guinea-Bissau", value: "Guinea-Bissau", label: "Guinea-Bissau" },
  { key: "Guyana", value: "Guyana", label: "Guyana" },
  { key: "Haiti", value: "Haiti", label: "Haiti" },
  { key: "Holy See", value: "Holy See", label: "Holy See" },
  { key: "Honduras", value: "Honduras", label: "Honduras" },
  { key: "Hungary", value: "Hungary", label: "Hungary" },
  { key: "Iceland", value: "Iceland", label: "Iceland" },
  { key: "India", value: "India", label: "India" },
  { key: "Indonesia", value: "Indonesia", label: "Indonesia" },
  { key: "Iran", value: "Iran", label: "Iran" },
  { key: "Iraq", value: "Iraq", label: "Iraq" },
  { key: "Ireland", value: "Ireland", label: "Ireland" },
  { key: "Israel", value: "Israel", label: "Israel" },
  { key: "Italy", value: "Italy", label: "Italy" },
  { key: "Jamaica", value: "Jamaica", label: "Jamaica" },
  { key: "Japan", value: "Japan", label: "Japan" },
  { key: "Jordan", value: "Jordan", label: "Jordan" },
  { key: "Kazakhstan", value: "Kazakhstan", label: "Kazakhstan" },
  { key: "Kenya", value: "Kenya", label: "Kenya" },
  { key: "Kiribati", value: "Kiribati", label: "Kiribati" },
  { key: "Kuwait", value: "Kuwait", label: "Kuwait" },
  { key: "Kyrgyzstan", value: "Kyrgyzstan", label: "Kyrgyzstan" },
  { key: "Laos", value: "Laos", label: "Laos" },
  { key: "Latvia", value: "Latvia", label: "Latvia" },
  { key: "Lebanon", value: "Lebanon", label: "Lebanon" },
  { key: "Lesotho", value: "Lesotho", label: "Lesotho" },
  { key: "Liberia", value: "Liberia", label: "Liberia" },
  { key: "Libya", value: "Libya", label: "Libya" },
  { key: "Liechtenstein", value: "Liechtenstein", label: "Liechtenstein" },
  { key: "Lithuania", value: "Lithuania", label: "Lithuania" },
  { key: "Luxembourg", value: "Luxembourg", label: "Luxembourg" },
  { key: "Madagascar", value: "Madagascar", label: "Madagascar" },
  { key: "Malawi", value: "Malawi", label: "Malawi" },
  { key: "Malaysia", value: "Malaysia", label: "Malaysia" },
  { key: "Maldives", value: "Maldives", label: "Maldives" },
  { key: "Mali", value: "Mali", label: "Mali" },
  { key: "Malta", value: "Malta", label: "Malta" },
  { key: "Marshall Islands", value: "Marshall Islands", label: "Marshall Islands" },
  { key: "Mauritania", value: "Mauritania", label: "Mauritania" },
  { key: "Mauritius", value: "Mauritius", label: "Mauritius" },
  { key: "Mexico", value: "Mexico", label: "Mexico" },
  { key: "Micronesia", value: "Micronesia", label: "Micronesia" },
  { key: "Moldova", value: "Moldova", label: "Moldova" },
  { key: "Monaco", value: "Monaco", label: "Monaco" },
  { key: "Mongolia", value: "Mongolia", label: "Mongolia" },
  { key: "Montenegro", value: "Montenegro", label: "Montenegro" },
  { key: "Morocco", value: "Morocco", label: "Morocco" },
  { key: "Mozambique", value: "Mozambique", label: "Mozambique" },
  { key: "Myanmar (formerly Burma)", value: "Myanmar (formerly Burma)", label: "Myanmar (formerly Burma)" },
  { key: "Namibia", value: "Namibia", label: "Namibia" },
  { key: "Nauru", value: "Nauru", label: "Nauru" },
  { key: "Nepal", value: "Nepal", label: "Nepal" },
  { key: "Netherlands", value: "Netherlands", label: "Netherlands" },
  { key: "New Zealand", value: "New Zealand", label: "New Zealand" },
  { key: "Nicaragua", value: "Nicaragua", label: "Nicaragua" },
  { key: "Niger", value: "Niger", label: "Niger" },
  { key: "Nigeria", value: "Nigeria", label: "Nigeria" },
  { key: "North Korea", value: "North Korea", label: "North Korea" },
  { key: "North Macedonia", value: "North Macedonia", label: "North Macedonia" },
  { key: "Norway", value: "Norway", label: "Norway" },
  { key: "Oman", value: "Oman", label: "Oman" },
  { key: "Pakistan", value: "Pakistan", label: "Pakistan" },
  { key: "Palau", value: "Palau", label: "Palau" },
  { key: "Palestine State", value: "Palestine State", label: "Palestine State" },
  { key: "Panama", value: "Panama", label: "Panama" },
  { key: "Papua New Guinea", value: "Papua New Guinea", label: "Papua New Guinea" },
  { key: "Paraguay", value: "Paraguay", label: "Paraguay" },
  { key: "Peru", value: "Peru", label: "Peru" },
  { key: "Philippines", value: "Philippines", label: "Philippines" },
  { key: "Poland", value: "Poland", label: "Poland" },
  { key: "Portugal", value: "Portugal", label: "Portugal" },
  { key: "Qatar", value: "Qatar", label: "Qatar" },
  { key: "Romania", value: "Romania", label: "Romania" },
  { key: "Russia", value: "Russia", label: "Russia" },
  { key: "Rwanda", value: "Rwanda", label: "Rwanda" },
  { key: "Saint Kitts and Nevis", value: "Saint Kitts and Nevis", label: "Saint Kitts and Nevis" },
  { key: "Saint Lucia", value: "Saint Lucia", label: "Saint Lucia" },
  { key: "Saint Vincent and the Grenadines", value: "Saint Vincent and the Grenadines", label: "Saint Vincent and the Grenadines" },
  { key: "Samoa", value: "Samoa", label: "Samoa" },
  { key: "San Marino", value: "San Marino", label: "San Marino" },
  { key: "Sao Tome and Principe", value: "Sao Tome and Principe", label: "Sao Tome and Principe" },
  { key: "Saudi Arabia", value: "Saudi Arabia", label: "Saudi Arabia" },
  { key: "Senegal", value: "Senegal", label: "Senegal" },
  { key: "Serbia", value: "Serbia", label: "Serbia" },
  { key: "Seychelles", value: "Seychelles", label: "Seychelles" },
  { key: "Sierra Leone", value: "Sierra Leone", label: "Sierra Leone" },
  { key: "Singapore", value: "Singapore", label: "Singapore" },
  { key: "Slovakia", value: "Slovakia", label: "Slovakia" },
  { key: "Slovenia", value: "Slovenia", label: "Slovenia" },
  { key: "Solomon Islands", value: "Solomon Islands", label: "Solomon Islands" },
  { key: "Somalia", value: "Somalia", label: "Somalia" },
  { key: "South Africa", value: "South Africa", label: "South Africa" },
  { key: "South Korea", value: "South Korea", label: "South Korea" },
  { key: "South Sudan", value: "South Sudan", label: "South Sudan" },
  { key: "Spain", value: "Spain", label: "Spain" },
  { key: "Sri Lanka", value: "Sri Lanka", label: "Sri Lanka" },
  { key: "Sudan", value: "Sudan", label: "Sudan" },
  { key: "Suriname", value: "Suriname", label: "Suriname" },
  { key: "Sweden", value: "Sweden", label: "Sweden" },
  { key: "Switzerland", value: "Switzerland", label: "Switzerland" },
  { key: "Syria", value: "Syria", label: "Syria" },
  { key: "Tajikistan", value: "Tajikistan", label: "Tajikistan" },
  { key: "Tanzania", value: "Tanzania", label: "Tanzania" },
  { key: "Thailand", value: "Thailand", label: "Thailand" },
  { key: "Timor-Leste", value: "Timor-Leste", label: "Timor-Leste" },
  { key: "Togo", value: "Togo", label: "Togo" },
  { key: "Tonga", value: "Tonga", label: "Tonga" },
  { key: "Trinidad and Tobago", value: "Trinidad and Tobago", label: "Trinidad and Tobago" },
  { key: "Tunisia", value: "Tunisia", label: "Tunisia" },
  { key: "Turkey", value: "Turkey", label: "Turkey" },
  { key: "Turkmenistan", value: "Turkmenistan", label: "Turkmenistan" },
  { key: "Tuvalu", value: "Tuvalu", label: "Tuvalu" },
  { key: "Uganda", value: "Uganda", label: "Uganda" },
  { key: "Ukraine", value: "Ukraine", label: "Ukraine" },
  { key: "United Arab Emirates", value: "United Arab Emirates", label: "United Arab Emirates" },
  { key: "United Kingdom", value: "United Kingdom", label: "United Kingdom" },
  { key: "United States of America", value: "United States of America", label: "United States of America" },
  { key: "Uruguay", value: "Uruguay", label: "Uruguay" },
  { key: "Uzbekistan", value: "Uzbekistan", label: "Uzbekistan" },
  { key: "Vanuatu", value: "Vanuatu", label: "Vanuatu" },
  { key: "Venezuela", value: "Venezuela", label: "Venezuela" },
  { key: "Vietnam", value: "Vietnam", label: "Vietnam" },
  { key: "Yemen", value: "Yemen", label: "Yemen" },
  { key: "Zambia", value: "Zambia", label: "Zambia" },
  { key: "Zimbabwe", value: "Zimbabwe", label: "Zimbabwe" },
];
