version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - ~/.ssh:/home/node/.ssh:ro
    command: sleep infinity
    network_mode: service:db
    env_file:
      - .env
      - .env.local
    environment:
      - POSTGRES_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DATABASE}?schema=public&connection_limit=10
      - POSTGRES_PRISMA_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DATABASE}?schema=public&connection_limit=10&pgbouncer=true
      - POSTGRES_URL_NON_POOLING=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DATABASE}?schema=public
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
  # minio:
  #   image: quay.io/minio/minio:RELEASE.2023-08-23T10-07-06Z # figure out which image to get
  #   command: server --console-address ":9001" http://minio{1...4}/data{1...2} # need to change the url
  #   expose:
  #     - "9000"
  #     - "9001"
  #   # environment:
  #     # MINIO_ROOT_USER: minioadmin # S3_ROOT_ACCESS_KEY in .env
  #     # MINIO_ROOT_PASSWORD: minioadmin # S3_ROOT_SECRET_KEY in .env
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
  #     interval: 30s
  #     timeout: 20s
  #     retries: 3
  #   hostname: minio1 # change naming here 
  #   volumes:
  #     - data1-1:/data1
  #     - data1-2:/data2

      # createbuckets:
      #   image: minio/mc
      #   depends_on:
      #     - minio
      #   entrypoint: >
      #     /bin/sh -c "
      #     /usr/bin/mc alias set myminio http://minio:9000 minio minio123;
      #     /usr/bin/mc mb myminio/somebucketname;
      #     /usr/bin/mc policy set public myminio/somebucketname;
      #     exit 0;
      #     "

volumes:
  postgres-data:
  # data1-1:
  # data1-2:
