version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - ~/.ssh:/home/node/.ssh:ro
    command: sleep infinity
    network_mode: service:db
    env_file:
      - .env
      - .env.local
    environment:
      - POSTGRES_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DATABASE}?schema=public&connection_limit=10
      - POSTGRES_PRISMA_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DATABASE}?schema=public&connection_limit=10&pgbouncer=true
      - POSTGRES_URL_NON_POOLING=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_SHADOW_HOST}/${POSTGRES_DATABASE}?schema=public
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
  shadow-db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - shadow-postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
  minio:
    image: quay.io/minio/minio:RELEASE.2023-08-23T10-07-06Z # figure out which image to get
    command: server --console-address ":9001" /data/minio # need to change the url
    ports:
      - 9090:9000
      - 9091:9001
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: ${S3_ROOT_ACCESS_KEY} # S3_ROOT_ACCESS_KEY in .env
      MINIO_ROOT_PASSWORD: ${S3_ROOT_SECRET_KEY} # S3_ROOT_SECRET_KEY in .env
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:9000/minio/health/live"
        ]
      interval: 30s
      timeout: 20s
      retries: 3
    hostname: minio1 # change naming here
    volumes:
      - data1-1:/data1
      - data1-2:/data2

  createbuckets:
    image: minio/mc
    env_file:
      - .env
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "echo ${S3_BUCKET_NAME}; /usr/bin/mc alias set myminio http://minio:9000 ${S3_ROOT_ACCESS_KEY} ${S3_ROOT_SECRET_KEY}; /usr/bin/mc mb myminio/${S3_BUCKET_NAME}; /usr/bin/mc policy set public myminio/${S3_BUCKET_NAME}; exit 0; "

volumes:
  postgres-data:
  shadow-postgres-data:
  data1-1:
  data1-2:
